/**:
  ros__parameters:
    ifname: "can0"

    # ROS -> CAN: 0x100/0x101/0x102 を Int 配列で送るトピック名
    sub_int_bridge_topic: ["motor0_cmd", "motor1_cmd", "motor2_cmd"]
    sub_int_bridge_canid: [0x100, 0x101, 0x102]

    # 0x301 を Float 配列で送る
    sub_float_bridge_topic: ["angle_301"]
    sub_float_bridge_canid: [0x301]

    add_cmd_vel: false