/**:
  ros__parameters:

    input_topic: "joy"
    output_topic: "cmd_vel"

    # 最大速度
    max_vx: 2.0
    max_vy: 2.0
    max_omega: 3.14159265359

    # Joy axes の割り当て
    axis_linear_x: 0
    axis_linear_y: 1
    axis_angular_z: 3

    # 符号反転
    invert_linear_x: true
    invert_linear_y: false
    invert_angular_z: false

    # デッドゾーン
    deadzone: 0.05

    # Joyタイムアウト [s]
    joy_timeout: 0.1