/**:
  ros__parameters:
    ifname: "can0" # CANバスが同じならcan0のままでOKです

    # CAN -> ROS (ブリッジがPublishし、joint_state_publisher_dansaがSubscribeする)
    pub_float_bridge_topic: ["motor_step_feedback"]
    pub_float_bridge_canid: [0x301] # ★注意: ide用(0x300)と被らないIDに設定してください

    # pub_int_bridge_topic: ["test_i_p"]
    # pub_int_bridge_canid: [0x401]
    # pub_bytes_bridge_topic: ["test_b_p"]
    # pub_bytes_bridge_canid: [0x402]

   
    sub_float_bridge_topic: ["right_leg", "left_leg", "back_leg","leg_robomas"]
    sub_float_bridge_canid: [0x211, 0x212, 0x213,0x214] 

    pub_int_bridge_topic: ["onedlidar"] 
    pub_int_bridge_canid: [0x401]          

    # sub_int_bridge_topic: ["test_i_s"]
    # sub_int_bridge_canid: [0x404]
    # sub_bytes_bridge_topic: ["test_b_s"]
    # sub_bytes_bridge_canid: [0x405]

    add_cmd_vel: true
    cmd_vel_canid: 0x100        # add_cmd_velがfalseの場合無視
    cmd_vel_topic_name: "cmd_vel" # add_cmd_velがfalseの場合無視

    add_cmd_vel_feedback: false
    cmd_vel_feedback_canid: 0x101                   # add_cmd_vel_feedbackがfalseの場合無視
    cmd_vel_feedback_topic_name: "cmd_vel_feedback" # add_cmd_vel_feedbackがfalseの場合無視