/**:
  ros__parameters:
    ifname: "can0"

    # joy_changer の出力上限値
    handRotation_max: 120
    handRotation_min: -170
    handRotation_speed: 120.0
    ballHolder_max: 0
    ballHolder_min: -820
    ballHolder_speed: 200.0
    max_ejectionrpm: 10
    toggleDebounceSeconds: 0.05

    pub_float_bridge_topic: ["angle_feedback"]
    pub_float_bridge_canid: [0x350]
    # pub_int_bridge_topic: ["onedlidar","feedback_type"] 
    # pub_int_bridge_canid: [0x401,0x103]  
    # # pub_bytes_bridge_topic: ["test_b_p"]
    # # pub_bytes_bridge_canid: [0x402]

    # sub_float_bridge_topic: ["j1", "j2", "j3", "step_legs", "leg_robomas", "takano_hand", "takano_holder"]
    # sub_float_bridge_canid: [0x201, 0x202, 0x203, 0x211, 0x214, 0x220, 0x221]
    # CAN ID が決まり次第、以下のコメントを外して対応する ID を設定する
    sub_int_bridge_topic: ["robomasu", "ejection", "holder_servo"]
    sub_int_bridge_canid: [0x230, 0x130, 0x401]
    sub_bytes_bridge_topic: ["air_cylinder"]
    sub_bytes_bridge_canid: [0x104]

    add_cmd_vel: true
    cmd_vel_canid: 0x100        # add_cmd_velがfalseの場合無視
    cmd_vel_topic_name: "cmd_vel" # add_cmd_velがfalseの場合無視

    # add_cmd_vel_feedback: true
    # cmd_vel_feedback_canid: 0x101                   # add_cmd_vel_feedbackがfalseの場合無視
    # cmd_vel_feedback_topic_name: "cmd_vel_feedback" # add_cmd_vel_feedbackがfalseの場合無視
