geometry_msgs/PoseStamped goal_pos
geometry_msgs/PoseStamped[] waypoints
float32 max_speed
float32 max_acc

bool enable_parallel
---
bool success
string msg
---
geometry_msgs/PoseStamped current
float32 pos_error
string msg